---
apiVersion: 1

deleteDatasources:
    - name: postgres-docker
      orgId: 1

datasources:
    - name: postgres-docker
      type: postgres
      url: postgres:5432
      database: postgres_test
      user: test
      secureJsonData:
          password: test
      jsonData:
          sslmode: disable
          maxOpenConns: 0
          maxIdleConns: 2
          connMaxLifetime: 14400
